### ISSUE TITLE
Robots somewhat small

### ISSUE THREAD

**Issue by HenriWahl** [blinkingnoise/roborally#4]
Hi there,
cool there comes some fresh movement into this nice implementation of the original boardgame! :+1: 

I just found the bots being a little bit too small - did this happen when using the new icons or are they meant to look that small?

**Comment by blinkingnoise** [comment]
Year, corna lockdown make it possible ;)

This is because with the smaller robots (80%) you can better see the board and you can also toggle tooltips of the tile.
See Commit 35c36138 style.sass

Maybe 90% will be the better...

**Comment by HenriWahl** [comment]
> Year, corna lockdown make it possible ;)

Yes, a lot of things got more attention. Likewise https://github.com/HenriWahl/doko3000 :-)

> This is because with the smaller robots (80%) you can better see the board and you can also toggle tooltips of the tile.
> See Commit [35c3613](https://github.com/blinkingnoise/roborally/commit/35c36138976c44e6818d02f1467ca43aca365fb2) style.sass

I added some screenshots from Roborally in Firefox on Linux. The poor robot looks a little bit lost. Pretty small and uncentered - that's why I wonder if it is meant this way.

![Bildschirmfoto vom 2021-02-01 19-33-05](https://user-images.githubusercontent.com/2835065/106502776-15ae2000-64c5-11eb-8d32-4436495a4fb3.png)

![Bildschirmfoto vom 2021-02-01 19-34-26](https://user-images.githubusercontent.com/2835065/106502783-18107a00-64c5-11eb-975b-04ff5ff57aba.png)

![Bildschirmfoto vom 2021-02-01 19-35-39](https://user-images.githubusercontent.com/2835065/106502787-1a72d400-64c5-11eb-90eb-00f3f4342028.png)

**Comment by blinkingnoise** [comment]
Now I have (hopefully) improved the robot placement. Furter i did some changes on respawn marker. The tooltip shows now the name of the player and i also removed the dynamic rotation.
![Auswahl_119](https://user-images.githubusercontent.com/7138036/107244162-02073a00-6a2e-11eb-85b2-ffacc7b18db8.png)

I do not know Doppelkopf but it look similar to "Bauernschnapsen" (Austria) and i will put on my server in the next days. The next lockdown will shurly come..
A keycloak integration will be a real improvement for RoboRally and DoDo3000 ;)

**Comment by HenriWahl** [comment]
Thanks, looks good!

After a short recherche I think Bauernschnapsen is different but looks funny too. :-)
